--
-- PostgreSQL database dump
--


-- Dumped from database version 15.15 (Debian 15.15-1.pgdg13+1)
-- Dumped by pg_dump version 15.14

-- Started on 2026-02-07 13:10:33 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 16390)
-- Name: tb_aep_report; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_aep_report (
    id bigint NOT NULL,
    evaluated_function character varying(255),
    evaluation_date date,
    pdf_path character varying(255),
    company_id bigint,
    evaluator_user_id bigint,
    physiotherapist_id bigint,
    sector_id bigint,
    unit_id bigint,
    sent_to_client_at timestamp(6) without time zone
);


--
-- TOC entry 214 (class 1259 OID 16389)
-- Name: tb_aep_report_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_aep_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_aep_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16397)
-- Name: tb_aep_selected_risks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_aep_selected_risks (
    report_id bigint NOT NULL,
    risk_description character varying(1024)
);


--
-- TOC entry 218 (class 1259 OID 16403)
-- Name: tb_agenda_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_agenda_event (
    id bigint NOT NULL,
    description oid,
    event_date date,
    event_type character varying(255),
    original_visit_date date,
    source_visit_id bigint,
    title character varying(255),
    user_id bigint,
    client_name character varying(255),
    manual_observation character varying(255),
    shift character varying(255) NOT NULL,
    technical_visit_id bigint,
    company_id bigint,
    CONSTRAINT tb_agenda_event_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['EVENTO'::character varying, 'TREINAMENTO'::character varying, 'VISITA_REAGENDADA'::character varying])::text[]))),
    CONSTRAINT tb_agenda_event_shift_check CHECK (((shift)::text = ANY ((ARRAY['MANHA'::character varying, 'TARDE'::character varying])::text[])))
);


--
-- TOC entry 217 (class 1259 OID 16402)
-- Name: tb_agenda_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_agenda_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_agenda_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 16800)
-- Name: tb_client; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_client (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255),
    access_code character varying(255),
    access_code_expiration timestamp(6) without time zone,
    password character varying(255)
);


--
-- TOC entry 244 (class 1259 OID 25809)
-- Name: tb_client_company; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_client_company (
    client_id bigint NOT NULL,
    company_id bigint NOT NULL
);


--
-- TOC entry 242 (class 1259 OID 16799)
-- Name: tb_client_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16412)
-- Name: tb_company; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_company (
    id bigint NOT NULL,
    cnpj character varying(255) NOT NULL,
    name character varying(255),
    client_id bigint
);


--
-- TOC entry 219 (class 1259 OID 16411)
-- Name: tb_company_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_company ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16420)
-- Name: tb_job_role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_job_role (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    company_id bigint
);


--
-- TOC entry 221 (class 1259 OID 16419)
-- Name: tb_job_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_job_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_job_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16426)
-- Name: tb_occupational_risk_report; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_occupational_risk_report (
    id bigint NOT NULL,
    inspection_date date,
    pdf_path character varying(255),
    technician_signature_image_base64 text,
    technician_signed_at timestamp(6) without time zone,
    title character varying(255),
    company_id bigint,
    sector_id bigint,
    technician_id bigint,
    unit_id bigint,
    sent_to_client_at timestamp(6) without time zone
);


--
-- TOC entry 223 (class 1259 OID 16425)
-- Name: tb_occupational_risk_report_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_occupational_risk_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_occupational_risk_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16434)
-- Name: tb_physiotherapist; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_physiotherapist (
    id bigint NOT NULL,
    crefito character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 225 (class 1259 OID 16433)
-- Name: tb_physiotherapist_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_physiotherapist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_physiotherapist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16442)
-- Name: tb_risk_evaluated_function; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_risk_evaluated_function (
    id bigint NOT NULL,
    function_name character varying(255),
    report_id bigint
);


--
-- TOC entry 227 (class 1259 OID 16441)
-- Name: tb_risk_evaluated_function_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_risk_evaluated_function ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_risk_evaluated_function_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16447)
-- Name: tb_risk_selected_codes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_risk_selected_codes (
    evaluated_function_id bigint NOT NULL,
    risk_code integer
);


--
-- TOC entry 231 (class 1259 OID 16451)
-- Name: tb_sector; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_sector (
    id bigint NOT NULL,
    name character varying(255),
    company_id bigint
);


--
-- TOC entry 230 (class 1259 OID 16450)
-- Name: tb_sector_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_sector ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_sector_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16457)
-- Name: tb_system_info; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_system_info (
    id bigint NOT NULL,
    cnpj character varying(255),
    company_name character varying(255),
    logo_base64 text
);


--
-- TOC entry 232 (class 1259 OID 16456)
-- Name: tb_system_info_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_system_info ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_system_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16465)
-- Name: tb_technical_visit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_technical_visit (
    id bigint NOT NULL,
    client_signature_image_base64 text,
    client_signature_latitude double precision,
    client_signature_longitude double precision,
    client_signed_at timestamp(6) without time zone,
    client_signer_name character varying(255),
    end_time time(6) without time zone,
    location character varying(255),
    next_visit_date date,
    pdf_path character varying(255),
    start_time time(6) without time zone,
    summary oid,
    technician_signature_image_base64 text,
    technician_signed_at timestamp(6) without time zone,
    title character varying(255),
    visit_date date,
    client_company_id bigint,
    sector_id bigint,
    technician_id bigint,
    unit_id bigint,
    sent_to_client_at timestamp(6) without time zone,
    next_visit_shift character varying(255),
    CONSTRAINT tb_technical_visit_next_visit_shift_check CHECK (((next_visit_shift)::text = ANY ((ARRAY['MANHA'::character varying, 'TARDE'::character varying])::text[])))
);


--
-- TOC entry 234 (class 1259 OID 16464)
-- Name: tb_technical_visit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_technical_visit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_technical_visit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16473)
-- Name: tb_unit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_unit (
    id bigint NOT NULL,
    cnpj character varying(255),
    name character varying(255),
    company_id bigint
);


--
-- TOC entry 236 (class 1259 OID 16472)
-- Name: tb_unit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_unit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_unit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 16481)
-- Name: tb_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_user (
    id bigint NOT NULL,
    birth_date date,
    conselho_classe character varying(255),
    cpf character varying(255),
    email character varying(255),
    especialidade character varying(255),
    name character varying(255),
    password character varying(255),
    password_reset_required boolean,
    phone character varying(255),
    role character varying(255) NOT NULL,
    sigla_conselho_classe character varying(255),
    certificate_password character varying(255),
    certificate_path character varying(255),
    CONSTRAINT tb_user_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying])::text[])))
);


--
-- TOC entry 238 (class 1259 OID 16480)
-- Name: tb_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 16490)
-- Name: tb_visit_finding; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_visit_finding (
    id bigint NOT NULL,
    consequences text,
    deadline date,
    description text,
    legal_guidance text,
    penalties text,
    photo_path1 character varying(255),
    photo_path2 character varying(255),
    priority character varying(255),
    recurrence boolean NOT NULL,
    responsible character varying(255),
    technical_visit_id bigint,
    CONSTRAINT tb_visit_finding_priority_check CHECK (((priority)::text = ANY ((ARRAY['BAIXA'::character varying, 'MEDIA'::character varying, 'ALTA'::character varying])::text[])))
);


--
-- TOC entry 240 (class 1259 OID 16489)
-- Name: tb_visit_finding_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_visit_finding ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_visit_finding_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3346 (class 2606 OID 16396)
-- Name: tb_aep_report tb_aep_report_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_aep_report
    ADD CONSTRAINT tb_aep_report_pkey PRIMARY KEY (id);


--
-- TOC entry 3348 (class 2606 OID 16410)
-- Name: tb_agenda_event tb_agenda_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_agenda_event
    ADD CONSTRAINT tb_agenda_event_pkey PRIMARY KEY (id);


--
-- TOC entry 3384 (class 2606 OID 25813)
-- Name: tb_client_company tb_client_company_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_client_company
    ADD CONSTRAINT tb_client_company_pkey PRIMARY KEY (client_id, company_id);


--
-- TOC entry 3382 (class 2606 OID 16806)
-- Name: tb_client tb_client_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_client
    ADD CONSTRAINT tb_client_pkey PRIMARY KEY (id);


--
-- TOC entry 3354 (class 2606 OID 16418)
-- Name: tb_company tb_company_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_company
    ADD CONSTRAINT tb_company_pkey PRIMARY KEY (id);


--
-- TOC entry 3358 (class 2606 OID 16424)
-- Name: tb_job_role tb_job_role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_job_role
    ADD CONSTRAINT tb_job_role_pkey PRIMARY KEY (id);


--
-- TOC entry 3360 (class 2606 OID 16432)
-- Name: tb_occupational_risk_report tb_occupational_risk_report_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_occupational_risk_report
    ADD CONSTRAINT tb_occupational_risk_report_pkey PRIMARY KEY (id);


--
-- TOC entry 3362 (class 2606 OID 16440)
-- Name: tb_physiotherapist tb_physiotherapist_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_physiotherapist
    ADD CONSTRAINT tb_physiotherapist_pkey PRIMARY KEY (id);


--
-- TOC entry 3366 (class 2606 OID 16446)
-- Name: tb_risk_evaluated_function tb_risk_evaluated_function_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_risk_evaluated_function
    ADD CONSTRAINT tb_risk_evaluated_function_pkey PRIMARY KEY (id);


--
-- TOC entry 3368 (class 2606 OID 16455)
-- Name: tb_sector tb_sector_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_sector
    ADD CONSTRAINT tb_sector_pkey PRIMARY KEY (id);


--
-- TOC entry 3370 (class 2606 OID 16463)
-- Name: tb_system_info tb_system_info_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_system_info
    ADD CONSTRAINT tb_system_info_pkey PRIMARY KEY (id);


--
-- TOC entry 3372 (class 2606 OID 16471)
-- Name: tb_technical_visit tb_technical_visit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_technical_visit
    ADD CONSTRAINT tb_technical_visit_pkey PRIMARY KEY (id);


--
-- TOC entry 3374 (class 2606 OID 16479)
-- Name: tb_unit tb_unit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_unit
    ADD CONSTRAINT tb_unit_pkey PRIMARY KEY (id);


--
-- TOC entry 3378 (class 2606 OID 16488)
-- Name: tb_user tb_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_user
    ADD CONSTRAINT tb_user_pkey PRIMARY KEY (id);


--
-- TOC entry 3380 (class 2606 OID 16497)
-- Name: tb_visit_finding tb_visit_finding_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_visit_finding
    ADD CONSTRAINT tb_visit_finding_pkey PRIMARY KEY (id);


--
-- TOC entry 3350 (class 2606 OID 16933)
-- Name: tb_agenda_event uk1cxkybxw9s9v1rwfe28ltq83; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_agenda_event
    ADD CONSTRAINT uk1cxkybxw9s9v1rwfe28ltq83 UNIQUE (technical_visit_id);


--
-- TOC entry 3352 (class 2606 OID 16499)
-- Name: tb_agenda_event ukgjkjx33s4pe0i7tlv2dhije11; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_agenda_event
    ADD CONSTRAINT ukgjkjx33s4pe0i7tlv2dhije11 UNIQUE (source_visit_id);


--
-- TOC entry 3376 (class 2606 OID 16505)
-- Name: tb_unit ukqio1a383rya5ulbkmxfrn8i7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_unit
    ADD CONSTRAINT ukqio1a383rya5ulbkmxfrn8i7 UNIQUE (cnpj);


--
-- TOC entry 3356 (class 2606 OID 16501)
-- Name: tb_company ukruse2bynlu533jtqlc6r4g4xh; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_company
    ADD CONSTRAINT ukruse2bynlu533jtqlc6r4g4xh UNIQUE (cnpj);


--
-- TOC entry 3364 (class 2606 OID 16503)
-- Name: tb_physiotherapist ukt8err3d1gaekhuan7afmjsb4t; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_physiotherapist
    ADD CONSTRAINT ukt8err3d1gaekhuan7afmjsb4t UNIQUE (crefito);


--
-- TOC entry 3394 (class 2606 OID 16807)
-- Name: tb_company fk159poo9hs21fom2aygwcaagjt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_company
    ADD CONSTRAINT fk159poo9hs21fom2aygwcaagjt FOREIGN KEY (client_id) REFERENCES public.tb_client(id);


--
-- TOC entry 3402 (class 2606 OID 16576)
-- Name: tb_sector fk3fgy8i0t4a7j8g8s2at14w3d8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_sector
    ADD CONSTRAINT fk3fgy8i0t4a7j8g8s2at14w3d8 FOREIGN KEY (company_id) REFERENCES public.tb_company(id);


--
-- TOC entry 3400 (class 2606 OID 16566)
-- Name: tb_risk_evaluated_function fk4gbxtkikrxhxgilcnb9ifngsp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_risk_evaluated_function
    ADD CONSTRAINT fk4gbxtkikrxhxgilcnb9ifngsp FOREIGN KEY (report_id) REFERENCES public.tb_occupational_risk_report(id);


--
-- TOC entry 3385 (class 2606 OID 16526)
-- Name: tb_aep_report fk4r771desqa2id19is5e2ughgt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_aep_report
    ADD CONSTRAINT fk4r771desqa2id19is5e2ughgt FOREIGN KEY (unit_id) REFERENCES public.tb_unit(id);


--
-- TOC entry 3386 (class 2606 OID 16516)
-- Name: tb_aep_report fk56hca8sr6a73m7pxvqj12kf4s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_aep_report
    ADD CONSTRAINT fk56hca8sr6a73m7pxvqj12kf4s FOREIGN KEY (physiotherapist_id) REFERENCES public.tb_physiotherapist(id);


--
-- TOC entry 3403 (class 2606 OID 16596)
-- Name: tb_technical_visit fk6572avxw2olcu3i0axk8vskkp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_technical_visit
    ADD CONSTRAINT fk6572avxw2olcu3i0axk8vskkp FOREIGN KEY (unit_id) REFERENCES public.tb_unit(id);


--
-- TOC entry 3396 (class 2606 OID 16561)
-- Name: tb_occupational_risk_report fk6k40quccw5fd2kher13m0ob3t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_occupational_risk_report
    ADD CONSTRAINT fk6k40quccw5fd2kher13m0ob3t FOREIGN KEY (unit_id) REFERENCES public.tb_unit(id);


--
-- TOC entry 3404 (class 2606 OID 16581)
-- Name: tb_technical_visit fk8rtpsmpy0wqgfv4xh3nhyany1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_technical_visit
    ADD CONSTRAINT fk8rtpsmpy0wqgfv4xh3nhyany1 FOREIGN KEY (client_company_id) REFERENCES public.tb_company(id);


--
-- TOC entry 3391 (class 2606 OID 16536)
-- Name: tb_agenda_event fk9145t7s1jqllsu5pmag86ta1a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_agenda_event
    ADD CONSTRAINT fk9145t7s1jqllsu5pmag86ta1a FOREIGN KEY (user_id) REFERENCES public.tb_user(id);


--
-- TOC entry 3397 (class 2606 OID 16551)
-- Name: tb_occupational_risk_report fk96aoa9yfmlufxofo5n8oi4fox; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_occupational_risk_report
    ADD CONSTRAINT fk96aoa9yfmlufxofo5n8oi4fox FOREIGN KEY (sector_id) REFERENCES public.tb_sector(id);


--
-- TOC entry 3398 (class 2606 OID 16556)
-- Name: tb_occupational_risk_report fkaq9sbkbaam1dmh9rfant8lgs6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_occupational_risk_report
    ADD CONSTRAINT fkaq9sbkbaam1dmh9rfant8lgs6 FOREIGN KEY (technician_id) REFERENCES public.tb_user(id);


--
-- TOC entry 3407 (class 2606 OID 16601)
-- Name: tb_unit fkcyul7rohf4s0q6h4rc1g44sln; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_unit
    ADD CONSTRAINT fkcyul7rohf4s0q6h4rc1g44sln FOREIGN KEY (company_id) REFERENCES public.tb_company(id);


--
-- TOC entry 3401 (class 2606 OID 16571)
-- Name: tb_risk_selected_codes fkdo1pld4u6l0in6nxk2hg56yly; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_risk_selected_codes
    ADD CONSTRAINT fkdo1pld4u6l0in6nxk2hg56yly FOREIGN KEY (evaluated_function_id) REFERENCES public.tb_risk_evaluated_function(id);


--
-- TOC entry 3392 (class 2606 OID 25814)
-- Name: tb_agenda_event fke7a2np5m4kf8o721tp3re4vpx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_agenda_event
    ADD CONSTRAINT fke7a2np5m4kf8o721tp3re4vpx FOREIGN KEY (company_id) REFERENCES public.tb_company(id);


--
-- TOC entry 3395 (class 2606 OID 16541)
-- Name: tb_job_role fkei0r3h98my53jlwmkurc8r0oc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_job_role
    ADD CONSTRAINT fkei0r3h98my53jlwmkurc8r0oc FOREIGN KEY (company_id) REFERENCES public.tb_company(id);


--
-- TOC entry 3387 (class 2606 OID 16521)
-- Name: tb_aep_report fkfqvk04wjimcm04dteykw2732h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_aep_report
    ADD CONSTRAINT fkfqvk04wjimcm04dteykw2732h FOREIGN KEY (sector_id) REFERENCES public.tb_sector(id);


--
-- TOC entry 3409 (class 2606 OID 25824)
-- Name: tb_client_company fkgmuc3wd2ajy5xkpbiq9xyj2xn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_client_company
    ADD CONSTRAINT fkgmuc3wd2ajy5xkpbiq9xyj2xn FOREIGN KEY (client_id) REFERENCES public.tb_client(id);


--
-- TOC entry 3399 (class 2606 OID 16546)
-- Name: tb_occupational_risk_report fkhfdhvxm4y9lp6du7091kys3re; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_occupational_risk_report
    ADD CONSTRAINT fkhfdhvxm4y9lp6du7091kys3re FOREIGN KEY (company_id) REFERENCES public.tb_company(id);


--
-- TOC entry 3405 (class 2606 OID 16586)
-- Name: tb_technical_visit fklg5gk0ijswjrl22gvbd186hcq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_technical_visit
    ADD CONSTRAINT fklg5gk0ijswjrl22gvbd186hcq FOREIGN KEY (sector_id) REFERENCES public.tb_sector(id);


--
-- TOC entry 3390 (class 2606 OID 16531)
-- Name: tb_aep_selected_risks fkmalqe3ojesio49acvh3g4xkp9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_aep_selected_risks
    ADD CONSTRAINT fkmalqe3ojesio49acvh3g4xkp9 FOREIGN KEY (report_id) REFERENCES public.tb_aep_report(id);


--
-- TOC entry 3410 (class 2606 OID 25819)
-- Name: tb_client_company fkn8qo7ei1d6bcif8049fg2p5ae; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_client_company
    ADD CONSTRAINT fkn8qo7ei1d6bcif8049fg2p5ae FOREIGN KEY (company_id) REFERENCES public.tb_company(id);


--
-- TOC entry 3388 (class 2606 OID 16511)
-- Name: tb_aep_report fknerigdoa9vvi33ubkj977elvy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_aep_report
    ADD CONSTRAINT fknerigdoa9vvi33ubkj977elvy FOREIGN KEY (evaluator_user_id) REFERENCES public.tb_user(id);


--
-- TOC entry 3389 (class 2606 OID 16506)
-- Name: tb_aep_report fkonuxc3cpwdufg28rbyo5ksl7g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_aep_report
    ADD CONSTRAINT fkonuxc3cpwdufg28rbyo5ksl7g FOREIGN KEY (company_id) REFERENCES public.tb_company(id);


--
-- TOC entry 3393 (class 2606 OID 16934)
-- Name: tb_agenda_event fkp96mp8je2orow6tjj1jipfwm7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_agenda_event
    ADD CONSTRAINT fkp96mp8je2orow6tjj1jipfwm7 FOREIGN KEY (technical_visit_id) REFERENCES public.tb_technical_visit(id);


--
-- TOC entry 3406 (class 2606 OID 16591)
-- Name: tb_technical_visit fkqgcgc9yw8nnidsprkn8x5pntw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_technical_visit
    ADD CONSTRAINT fkqgcgc9yw8nnidsprkn8x5pntw FOREIGN KEY (technician_id) REFERENCES public.tb_user(id);


--
-- TOC entry 3408 (class 2606 OID 16606)
-- Name: tb_visit_finding fkr57wrmg51npgv1u3uk133pnub; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_visit_finding
    ADD CONSTRAINT fkr57wrmg51npgv1u3uk133pnub FOREIGN KEY (technical_visit_id) REFERENCES public.tb_technical_visit(id);


-- Completed on 2026-02-07 13:10:33 UTC

--
-- PostgreSQL database dump complete
--


